version: '3'

services:
  react:
    build:
      context: ..
      dockerfile: "docker/Dockerfile"
    image: csc309-react:1.13
    container_name: csc309-react-frontend
    restart: unless-stopped
    ports:
      - "7120:80"
    environment:
      - "TZ=America/Toronto"